spring:
  datasource:
    name: test  #\u6570\u636E\u5E93\u540D
    url: jdbc:mysql://localhost:3306/test #url
    username: root  #\u7528\u6237\u540D
    password:   #\u5BC6\u7801
    driver-class-name: com.mysql.cj.jdbc.Driver #\u6570\u636E\u5E93\u9A71\u52A8
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  #启动热加载
  devtools:
  restart-enabled: true
  #设置重启的目录，检索目录(resources/static、resources/templates)
  restart-additional-paths: src/main/java
  #classpath目录下的WEB-INF文件夹内容修改不重启
  #restart-exclude: WEB-INF/**
  #指定mapper路径，指定数据库映射类路径
mybatis:
  mapper-locations: classpath:mapper/*.xml  #\u914D\u7F6E\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.example.demo.bean #\u914D\u7F6E\u5B9E\u4F53\u7C7B
  #开启下划线转驼峰
  configuration:
      map-underscore-to-camel-case: true